language: python
dist: xenial
python:
- '3.6'
before_install:
- sudo apt-get install pandoc
- cd tests/
#
# instructions: 
# https://docs.travis-ci.com/user/encrypting-files/#manual-encryption
#
# encrypt file with command:
# openssl aes-256-cbc -k "<your password>" -in super_secret.txt -out super_secret.txt.enc
#
# then add password to repository's travis settings as an environment var
# env var credentials_password should have value <your password>
# 
# decrypt files with command:
- openssl aes-256-cbc -k "$credentials_password" -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar xvf secrets.tar.gz
- cd ../
install:
- pip install -r requirements.txt
- python setup.py build install
script:
- cd tests/
- pytest
