language: python

python: 3.6
dist: xenial

addons:
  apt:
    packages:
    - pandoc

before_install:
#
# instructions: 
# https://docs.travis-ci.com/user/encrypting-files/#manual-encryption
#
# encrypt file with command:
# openssl aes-256-cbc -k "<your password>" -in super_secret.txt -out super_secret.txt.enc
#
# then add password to repository's travis settings as an environment var
# env var credentials_password should have value <your password>
# 
# decrypt files with command:
# - openssl aes-256-cbc -k "$credentials_password" -in secrets.tar.gz.enc -out secrets.tar.gz -d
- openssl aes-256-cbc -K $encrypted_1544067babfc_key -iv $encrypted_1544067babfc_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p /tmp/centillion

install:
- wget -q http://us-east-1.ec2.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-6_amd64.deb
- mkdir make4
- dpkg -x make*.deb make4
- export PATH=$(pwd)/make4/usr/bin:$PATH
- pip install -r requirements.txt
- python setup.py build install

script:
- make $MAKE_ARGS

stages:
- name: standalone_test
- name: integration_test

jobs:
  include:
  - stage: standalone_test
    env:
    - MAKE_ARGS="standalone_test"
  - stage: integration_test
    env:
    - MAKE_ARGS="integration_test"
